### PR TITLE
Fix tests failing due to pytest changes

### PR DESCRIPTION
**Pull request by aragilar**

### CODE REVIEW

**Comment by opoplawski** [comment]
Seems to fix tests for me with pytest 6.0.2, unless I'm running without any pytest plugins.  Does that make sense?

**Comment by opoplawski** [comment]
Nope, it was just user error.  Works for me.

**Comment by drew-parsons** [comment]
As far as I can tell the PR needs to add
```
--- pytest-mpi.orig/tests/test_markers.py       2021-01-23 00:55:32.883507876 +0100
+++ pytest-mpi/tests/test_markers.py    2021-01-23 01:02:05.074814005 +0100
@@ -22,7 +22,7 @@

         assert comm.size >= 4

-    @pytest.mark.mpi(2)
+    @pytest.mark.mpi(min_size=2)
     def test_size_fail_pos():
         from mpi4py import MPI
         comm = MPI.COMM_WORLD
```
for test_size_fail_pos.

Otherwise it still gives the error
```
>                   raise ValueError("mpi mark does not take positional args")
E                   ValueError: mpi mark does not take positional args
```

**Pull request merged**
